#!/bin/bash

/bin/chmod 644 /Library/LaunchDaemons/com.ws1.migrator.plist
/bin/launchctl unload /Library/LaunchDaemons/com.ws1.migrator.plist
/bin/launchctl load /Library/LaunchDaemons/com.ws1.migrator.plist

chmod +x /usr/local/bin/jq
chmod +x /Library/Application\ Support/WS1/migrator.sh
chmod +x /Library/Application\ Support/WS1/MigratorResources/*
chmod +x /Applications/Utilities/DEPNotify.app/Contents/MacOS/DEPNotify
xattr -dr com.apple.quarantine /usr/local/bin/jq

exit 0
