#!/bin/bash

chmod +x /usr/local/bin/jq
chmod +x /Library/Application\ Support/WS1/migrator.sh
chmod +x /Library/Application\ Support/WS1/MigratorResources/*
chmod +x /Applications/Utilities/DEPNotify.app/Contents/MacOS/DEPNotify
/bin/chmod -R 555 /Library/Application\ Support/WS1
xattr -dr com.apple.quarantine /usr/local/bin/jq

sleep 1

/bin/chmod 644 /Library/LaunchDaemons/com.ws1.migrator.plist
/bin/launchctl unload /Library/LaunchDaemons/com.ws1.migrator.plist
sleep 2
/bin/launchctl load /Library/LaunchDaemons/com.ws1.migrator.plist

exit 0
