---
# defaults file for permissions
api_endpoints:
  list_permissions : "/config/v1/permissions"
  assign_permissions: "/config/v1/permissions" 

assign_permissions:
  ad_user_or_group_id: "S-1-5-21-3949112806-1985708904-1648417161-500"
  local_access_group_id: "d6dc0a92-243b-4d17-ad5d-ed11e840e7f4"