---
# tasks file for install_connection_server
- name: Invoke Install Connection Server
  uri:
    url: "{{ api_base_url }}{{ api_endpoints.install_connection_server }}"
    method: POST
    headers:
      Authorization: "Bearer {{ token }}"
    body_format: json
    body: >-
      {{
        {
          "domain": install_parameters.domain,
          "password": install_parameters.password,
          "server_installer_package_id": package_id,
          "server_msi_install_spec": {
            "fips_enabled": install_parameters.server_msi_install_spec.fips_enabled,
            "fw_choice": install_parameters.server_msi_install_spec.fw_choice,
            "install_directory": install_parameters.server_msi_install_spec.install_directory,
            "server_instance_type": "ENROLLMENT_SERVER",
            "vdm_ipprotocol_usage": install_parameters.server_msi_install_spec.vdm_ipprotocol_usage
          },
          "target_server_fqdn": item,
          "user_name": install_parameters.user_name
        }
      }}
    status_code: 204
    validate_certs: no
  register: install_response
  environment:
    CURL_CA_BUNDLE: ""
    REQUESTS_CA_BUNDLE: ""
  loop: "{{ enrollment_servers }}"
  loop_control:
    label: "{{ item }}"


- name: Assert each install API response returned status 204
  assert:
    that:
      - item.status == 204
    fail_msg: "Install failed for {{ item.item }}: expected status 204, got {{ item.status }}"
    success_msg: "Install API call for {{ item.item }} succeeded with status 204"
  loop: "{{ install_response.results }}"
  loop_control:
    label: "{{ item.item }}"

- name: Set fact for failed installations
  set_fact:
    failed_enrollment_servers: "{{ failed_enrollment_servers | default([]) + [item.item] }}"
  when: item.status != 204
  loop: "{{ install_response.results }}"


