name: update-readme-summary-table

# on: [workflow_dispatch]
on:
  push:
    branches: 
      - staging
  workflow_dispatch:

jobs:
    build:
      runs-on: ubuntu-latest

      permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
        contents: write

      steps:
#        - uses: actions/checkout@v1
        - name: Checkout repo to the runner
          uses: actions/checkout@v4

        - name: Run update-readme-summary-table.ps1 Script
          run: ./update-readme-summary-table.ps1
          shell: pwsh

        - name: Commit all changed files back to the repository
          uses: stefanzweifel/git-auto-commit-action@v5
          with:
            # Optional. Commit message for the created commit.
            # Defaults to "Apply automatic changes"
            commit_message: "Update docs/index.md, docs/*/*index.md files"

            # Optional. Local and remote branch name where commit is going to be pushed
            #  to. Defaults to the current branch.
            #  You might need to set `create_branch: true` if the branch does not exist.
            branch: staging

            # Optional. Options used by `git-commit`.
            # See https://git-scm.com/docs/git-commit#_options
            commit_options: '--no-verify --signoff'

            # Optional glob pattern of files which should be added to the commit
            # Defaults to all (.)
            # See the `pathspec`-documentation for git
            # - https://git-scm.com/docs/git-add#Documentation/git-add.txt-ltpathspecgt82308203
            # - https://git-scm.com/docs/gitglossary#Documentation/gitglossary.txt-aiddefpathspecapathspec
            file_pattern: 'docs/*/index.md docs/UEM-Samples/*-index.md'

            # Optional. Local file path to the repository.
            # Defaults to the root of the repository.
            repository: .

            # Optional commit user and author settings
            commit_user_name: Phil Helmling # defaults to "github-actions[bot]"
            commit_user_email: helmlingp@omnissa.com # defaults to "41898282+github-actions[bot]@users.noreply.github.com"
            commit_author: Phil Helmling <helmlingp@omnissa.com> # defaults to "username <username@users.noreply.github.com>", where "username" belongs to the author of the commit that triggered the run